a="My Captain_2021"
print(a.capitalize())
print(a.casefold())
print(a.center(25,'*'))
print(a.count('a'))
print(a.encode())
print(a.endswith('n'))
print(a.expandtabs())
print(a.find('o'))
print(a.find('y'))
print(a.index(' '))
print(a.isalnum())
print(a.isalpha())
print(a.isdecimal())
print(a.isdigit())
print(a.isidentifier())
print(a.islower())
print(a.isnumeric())
print(a.isprintable())
print(a.isspace())
print(a.istitle())
print(a.isupper())
print(a.ljust(18,'*'))
print(a.lower())
print(a.lstrip("My"))
print(a.partition('_'))
print(a.replace('_',' '))
print(a.rfind('a'))
print(a.rindex(' '))
print(a.rjust(18,'*'))
print(a.rpartition('2'))
print(a.rsplit('2'))
print(a.rstrip('2021'))
print(a.split('p'))
print(a.startswith('M'))
print(a.strip())
print(a.swapcase())
print(a.title())
print(a.upper())
print(a.zfill(20))
s=a.maketrans('cap','CAP')
print(s)
print(a.translate(s))
print('-'.join(a))
b="Name:{}"
print(b.format("SAM"))
c="apple\nmango"
print(c.splitlines())
d="Name1:{x},Name2:{y}"
e={'x':"SAMYU",'y':"NAVI"}
print(d.format_map(e))



